/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package campingcucao.mantenedores;
// FORANEA ZONA,PAGO EN CLIENTE
import campingcucao.principal.Principal;
import campingcucao.calculos.Calculo;
import campingcucao.calculos.Conectar;
import campingcucao.calculos.Conectar;
import static java.lang.String.valueOf;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Mauricio
 */
public class Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Administracion
     */
    public Cliente() {
        initComponents();
        CargarTabla("");
        CargarCB();
        btnAceptar.setVisible(false);
        btnCancelar.setVisible(false);
        txtPrecioZona.setEnabled(false);
        txtTotal.setEnabled(false);
        
        txtID.setEnabled(false);
        txtNombre.setEnabled(false);
        txtFono.setEnabled(false);
        txtMail.setEnabled(false);
        txtDias.setEnabled(false);  
        cbZona.setEnabled(false);
    }
    
 

    void CargarTabla(String dato){
        Statement st;
        String sql;
        
        try {
            
            st = cn.createStatement();
            String columnas;  //TITULOS DE TABLA
            if(dato.equals("")){
                sql = "SELECT * FROM tCliente"; 
            }else{
                sql = "SELECT * FROM tCliente WHERE idCliente LIKE '%"+dato+"%'";                 
            }
            ResultSet rsTB = st.executeQuery(sql);
            ResultSetMetaData rsMD = rsTB.getMetaData();
            int col = rsMD.getColumnCount();
            DefaultTableModel modelo = new DefaultTableModel();
            this.tbTabla.setModel(modelo);
            for(int i=1;i<=col;i++){
                modelo.addColumn(rsMD.getColumnLabel(i));    //ENCABEZADOS DE TABLA   
            }
            while(rsTB.next()){
                String fil[] = new String[col];
                for(int j=0;j<col;j++){
                    fil[j] = rsTB.getString(j+1);
                }
                modelo.addRow(fil);
            }   
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
     void CargarCB(){

        try {
            Statement st = cn.createStatement();
            String sql= "Select * from tZona";
            ResultSet rsCB = st.executeQuery(sql);
            while(rsCB.next()){
                cbZona.addItem(rsCB.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            //rsCB.close();
        }
     }
       
        
    
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgTipo = new javax.swing.ButtonGroup();
        panel1 = new java.awt.Panel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        lblNom = new javax.swing.JLabel();
        lblFono = new javax.swing.JLabel();
        lblMail = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtID = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtNombre = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtFono = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtMail = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbTabla = new javax.swing.JTable();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblDias = new javax.swing.JLabel();
        cbZona = new javax.swing.JComboBox<>();
        lblZona1 = new javax.swing.JLabel();
        txtDias = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        lblTotal1 = new javax.swing.JLabel();
        txtPrecioZona = new javax.swing.JTextField();
        txtBuscar = new javax.swing.JTextField();
        lblBuscar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(51, 51, 255));
        panel1.setName(""); // NOI18N
        panel1.setPreferredSize(new java.awt.Dimension(996, 454));

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setText("MODIFICAR");
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblID.setForeground(new java.awt.Color(51, 153, 255));
        lblID.setText("ID Cliente");

        lblNom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNom.setForeground(new java.awt.Color(51, 153, 255));
        lblNom.setText("Nombre");

        lblFono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFono.setForeground(new java.awt.Color(51, 153, 255));
        lblFono.setText("Fono");

        lblMail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMail.setForeground(new java.awt.Color(51, 153, 255));
        lblMail.setText("Mail");

        jScrollPane2.setViewportView(txtID);

        jScrollPane4.setViewportView(txtNombre);

        jScrollPane5.setViewportView(txtFono);

        jScrollPane6.setViewportView(txtMail);

        tbTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTablaMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tbTabla);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblDias.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDias.setForeground(new java.awt.Color(51, 153, 255));
        lblDias.setText("Dias");

        cbZona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Zona" }));
        cbZona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbZonaMouseClicked(evt);
            }
        });
        cbZona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbZonaActionPerformed(evt);
            }
        });

        lblZona1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblZona1.setForeground(new java.awt.Color(51, 153, 255));
        lblZona1.setText("Zona");

        txtDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiasActionPerformed(evt);
            }
        });
        txtDias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiasKeyReleased(evt);
            }
        });

        lblPrecio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(51, 153, 255));
        lblPrecio.setText("Precio Zona");

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        lblTotal1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotal1.setForeground(new java.awt.Color(51, 153, 255));
        lblTotal1.setText("Total");

        txtPrecioZona.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPrecioZonaFocusGained(evt);
            }
        });
        txtPrecioZona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioZonaActionPerformed(evt);
            }
        });

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        lblBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(51, 153, 255));
        lblBuscar.setText("Ingrese ID a buscar:");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblZona1)
                        .addGap(378, 378, 378))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNom)
                                    .addComponent(lblMail)
                                    .addComponent(lblFono)
                                    .addComponent(lblDias, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(txtDias, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(lblTotal1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                            .addComponent(jScrollPane5)
                                            .addGroup(panel1Layout.createSequentialGroup()
                                                .addComponent(cbZona, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33)
                                                .addComponent(lblPrecio)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtPrecioZona, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane6)))))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(lblID)
                                .addGap(38, 38, 38)
                                .addComponent(jScrollPane2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addGap(29, 29, 29)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(lblBuscar)
                        .addGap(45, 45, 45)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(77, 77, 77))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblFono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblZona1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecioZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregar)
                            .addComponent(btnModificar)
                            .addComponent(btnEliminar)
                            .addComponent(btnSalir)))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAceptar)
                        .addComponent(btnCancelar)))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        Principal P = new Principal();
        P.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        txtID.setEnabled(true);
        txtNombre.setEnabled(true);
        txtFono.setEnabled(true);
        txtMail.setEnabled(true);
        txtDias.setEnabled(true);
        btnAceptar.setVisible(true);
        btnCancelar.setVisible(true);
        btnAgregar.setVisible(true);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnSalir.setEnabled(false);
        cbZona.setEnabled(true);

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tbTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTablaMouseClicked
        int fil = tbTabla.getSelectedRow();
       
        
        if(fil >=0){
  
            txtID.setText(tbTabla.getValueAt(fil, 0).toString());
            
            txtNombre.setText(tbTabla.getValueAt(fil, 1).toString());
            txtFono.setText(tbTabla.getValueAt(fil, 2).toString());
            txtMail.setText(tbTabla.getValueAt(fil, 3).toString());
            
        }
    }//GEN-LAST:event_tbTablaMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
        txtNombre.setEnabled(true);
        txtFono.setEnabled(true);
        txtMail.setEnabled(true);
        txtDias.setEnabled(true);
        cbZona.setEnabled(true);
        btnAgregar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnSalir.setEnabled(false);
        btnAceptar.setVisible(true);
        btnCancelar.setVisible(true);
        btnModificar.setEnabled(true);
        txtID.setEnabled(false);
    }//GEN-LAST:event_btnModificarMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        btnEliminar.setEnabled(true);
        btnSalir.setEnabled(true);
        btnAceptar.setVisible(false);
        btnCancelar.setVisible(false);
        btnAgregar.setEnabled(true);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
        cbZona.setEnabled(false);

        txtID.setEnabled(false);
        txtNombre.setEnabled(false);
        txtFono.setEnabled(false);
        txtMail.setEnabled(false);
        txtDias.setEnabled(false);  
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
              

            PreparedStatement pst,pstP;
            if (btnAgregar.isEnabled()){
                try {
                    pst = cn.prepareStatement("INSERT INTO tCliente(idCliente,nomCliente,fonoCliente,mailCliente) VALUES(?,?,?,?)");
                    pst.setString(1,txtID.getText());
                    pst.setString(2,txtNombre.getText());
                    pst.setInt(3,Integer.parseInt(txtFono.getText()));
                    pst.setString(4,txtMail.getText());
                    pst.executeUpdate();
                    CargarTabla("");
                    
                    pstP = cn.prepareStatement("INSERT INTO tPago(idPago,idCliente,idZona,totalPago) VALUES(?,?,?,?)");
                    pstP.setString(1,txtID.getText() + cbZona.getSelectedItem().toString());
                    pstP.setString(2,txtID.getText());
                    pstP.setString(3,cbZona.getSelectedItem().toString());
                    pstP.setInt(4,Integer.parseInt(txtTotal.getText()));
                    pstP.executeUpdate();
                    
                    JOptionPane.showMessageDialog(null,"Datos Ingresados Correctamente","Correcto", JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,"Datos Incorrectos" + " " + ex,"ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }if (btnModificar.isEnabled() ){
                try {
                    pst = cn.prepareStatement("UPDATE tCliente SET nomCliente='"+txtNombre.getText()+"',fonoCliente='"+txtFono.getText()+"',mailCliente='"+txtMail.getText()+"' WHERE idCliente='"+txtID.getText()+"'");
                    pst.executeUpdate();
                    
                    pstP = cn.prepareStatement("UPDATE tPago SET totalPago= '"+Integer.parseInt(txtTotal.getText())+"' WHERE idCliente='"+txtID.getText()+"'");
                    pstP.executeUpdate();
                    CargarTabla("");
                    JOptionPane.showMessageDialog(null,"Datos Modificados Correctamente","Correcto", JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException ex) { 
                    Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            btnEliminar.setEnabled(true);
            btnSalir.setEnabled(true);
            btnAceptar.setVisible(false);
            btnCancelar.setVisible(false);
            btnAgregar.setEnabled(true);
            btnModificar.setEnabled(true);
            btnEliminar.setEnabled(true);
            cbZona.setEnabled(false);

            txtID.setEnabled(false);
            txtNombre.setEnabled(false);
            txtFono.setEnabled(false);
            txtMail.setEnabled(false);
            txtDias.setEnabled(false);
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int r = JOptionPane.showConfirmDialog(null,"Seguro que desea eliminar?","Eliminar",JOptionPane.YES_NO_OPTION );
        if(r == 0){
            PreparedStatement pst,pstP;
            try {
                pst = cn.prepareStatement("DELETE FROM tCliente WHERE idCliente='"+txtID.getText()+"'");
                pstP = cn.prepareStatement("DELETE FROM tCliente WHERE idCliente='"+txtID.getText()+"'");
                
                pst.executeUpdate();
                pstP.executeUpdate();
                CargarTabla("");
            } catch (SQLException ex) {
                Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtPrecioZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioZonaActionPerformed
        
    }//GEN-LAST:event_txtPrecioZonaActionPerformed

    private void cbZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbZonaActionPerformed
        try {
            Statement st = cn.createStatement();
            String sql= "SELECT precioZona FROM tZona WHERE idZona = '"+cbZona.getSelectedItem().toString()+"'";
            ResultSet rsPZ = st.executeQuery(sql);
            if (rsPZ.next()){
            txtPrecioZona.setText(rsPZ.getString(1));
            }
            
           
        } catch (SQLException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Error en la BD"+ " "+ ex ,"Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_cbZonaActionPerformed

    private void cbZonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbZonaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbZonaMouseClicked

    private void txtPrecioZonaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecioZonaFocusGained
        
    }//GEN-LAST:event_txtPrecioZonaFocusGained

    private void txtDiasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiasKeyReleased
        String total = String.valueOf(c.getCalculo(Integer.parseInt(txtPrecioZona.getText()), Integer.parseInt(txtDias.getText())));
        
        txtTotal.setText(total);
        
        
    }//GEN-LAST:event_txtDiasKeyReleased

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        CargarTabla(txtBuscar.getText());
        
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiasActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Cliente().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgTipo;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbZona;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblDias;
    private javax.swing.JLabel lblFono;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTotal1;
    private javax.swing.JLabel lblZona1;
    private java.awt.Panel panel1;
    private javax.swing.JTable tbTabla;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDias;
    private javax.swing.JTextPane txtFono;
    private javax.swing.JTextPane txtID;
    private javax.swing.JTextPane txtMail;
    private javax.swing.JTextPane txtNombre;
    private javax.swing.JTextField txtPrecioZona;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
Conectar cc = new Conectar();
Connection cn = cc.conexion();
Calculo c = new Calculo();
}
